### ISSUE TITLE
MuseScore API no longer supported

### ISSUE THREAD

**Issue by jaysinh01** [eelcovdw/mono-MusicXML-dataset#1]
Hey I was trying to get the dataset, however it appears the MuseScore API is not longer supported. Would you have a local copy?

**Comment by eelcovdw** [comment]
Musescore had to remove their public API in 2018 due to DMCA, so the dataset is no longer available. Sadly, I don't have the permission from them to hand out the dataset  myself.

**Comment by jaysinh01** [comment]
Oh okay no worries. Thank you!
